name: build&deploy .net app

on:
  push:
    branches: [ "master" ]

jobs:
  release-app:
    runs-on: ubuntu-20.04
    steps:
    - name: clone source code
      uses: actions/checkout@v4
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: build&package application
      run: |
        echo "build dotnet app now..."
        dotnet publish --configuration Release --runtime linux-x64 --self-contained true --output ./release
        echo "package dotnet app now..."
        zip -q -r release.zip ./release
    - name: transfer file via scp...
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        port: ${{ secrets.VPS_PORT }}
        key: ${{ secrets.VPS_KEY }}
        source: ./release.zip
        target: /home/github-actions/
    - name: execute commands via ssh...
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        port: ${{ secrets.VPS_PORT }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /home/github-actions/
          ls -lah
