name: dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release-app:
    runs-on: ubuntu-20.04
    steps:
    - name: clone source code
      uses: actions/checkout@v4
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: build&package application
      run: |
        echo "build dotnet app now..."
        dotnet publish --configuration Release --runtime linux-x64 --self-contained true --output ./release
        echo "package dotnet app now..."
        zip -q -r release.zip ./release
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app-release
        path: ./release.zip
        overwrite: true
