name: dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone the repo
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Publish app
      run: dotnet publish --configuration Release --runtime linux-x64 --self-contained true --output ./release
    - name: List current dir
      run: ls -lah
    - name: Package dist
      run: zip -r release.zip ./release
    - name: List current dir
      run: ls -lah
